### ISSUE TITLE
the exact formula of AHP@k?

### ISSUE THREAD

**Issue by iTomxy** [cvjena/semantic-embeddings#4]
Hi,
I don't understand the formula used in the codes [here](https://github.com/cvjena/semantic-embeddings/blob/f80885fe5b835b03979aadcebbad85cfefdb70d8/class_hierarchy.py#L307).
I can recognize that the first term is the average of {HP@i} for i from 1 to k, but what is the second term?
Can you provide the exact formula of AHP@k ?
thanks

**Comment by Callidior** [comment]
Hello,

AHP@k is computed as the area under the hierarchical precision (`HP@k'`) curve over the interval `k' ∈ [1, k]` using the trapezoidal rule and then divided by `k` to normalize the x-axis to the range `[0, 1]`, so that all AHP@k values fall into that range as well.

Thus, the equation for computing AHP@k is:

![AHP@k = 1/k * ( (sum_(i=1)^k HP@i) - 1/2 * (HP@1 + HP@k) )](https://render.githubusercontent.com/render/math?math=%5Cmathrm%7BAHP%7D%40k%20%3D%20%5Cfrac%7B1%7D%7Bk%7D%20%5Cleft%5B%20%5Cleft(%20%5Csum_%7Bi%3D1%7D%5Ek%20%5Cmathrm%7BHP%7D%40i%20%5Cright)%20-%20%5Cfrac%7B%5Cmathrm%7BHP%7D%401%20%2B%20%5Cmathrm%7BHP%7D%40k%7D%7B2%7D%20%5Cright%5D)

However, there was a bug in the code regarding the last term of the equation (`-HP@k / 2`) which is now fixed. This decreased the mAHP@250 of all methods by between 0.001 and 0.002. The ranking of the methods was hence not affected by these minor adjustments.
